name: Integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Log Node.js version
        run: node -v

      - name: Setup Bun
        # https://github.com/oven-sh/setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Log Node.js version
        run: node -v

      - name: Log Bun version
        run: bun -v

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run format
        run: bun run format

      - name: Run tests
        env:
          # https://github.com/starmode-base/neon-testing/settings/variables/actions
          # https://github.com/starmode-base/neon-testing/settings/secrets/actions
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
        run: bun run test
